import Logout from '@/components/auth/Logout';
import { useAuth } from '@/hooks/useAuth';
import Head from 'next/head';
import GetOwnAttendance from '@/components/GetOwnAttendance';
import WriteAttendance from '@/components/WriteAttendance';
import GetSortedData from '@/components/GetSortedData';
import { ToastContainer } from 'react-toastify';

export default function Home() {
  const { persist } = useAuth();

  if (!persist) return null;

  return (
    <>
      <Head>
        <title>Face recognition App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col items-center justify-center'>
        <h1 className='text-3xl font-bold underline text-red-500'>
          Hello GUYS!
        </h1>
        <Logout />
        <WriteAttendance />
        <GetOwnAttendance />
        <GetSortedData />
        <ToastContainer position='top-center' />
      </div>
    </>
  );
}

// TASK - 2023-3-31
// 1) userId-gaa context-aa awna. Login hiiheer
// 2) FRONTEND: Home page-eesee button darhar axios.post "/attendes" - url-aar body-oor ni userId bichne.
// 3) BACKEND: event.body userId awna, attendance table rvv bichne.
// 4) userId = partition key, createdAt = sort key (odoo tsagaa hadgalna)
// 4) createdAt, description dr == ireh estoi tsagaasaa - Date.now(). Hotsorson tuhai table dr hadgalna.
// 5) FRONTEND: backend-eesee hotsorson medeelellin data awna.

// ERD --> attendance table --> 1. userId, 2. createdAt 3. description
