service: aws-attendance-app
frameworkVersion: '3'

custom:
  table:
    users: Users
    attendance: Attendance
    images: Images
  s3:
    # bucket name MUST be unique!!!!!!. Otherwise it'll respond with "bucket already exists" error...
    bucket: attendance-image-bucket

  hash:
    userId: userId
    imageName: imageName

provider:
  name: aws
  runtime: nodejs16.x
  # Hong Kong ping was lower than any others. According to "https://www.cloudping.info/".
  # But REKOGNITION is not available for Hong Kong region...
  # region: ap-east-1
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - lambda:InvokeFunction
            - rekognition:CompareFaces
            # - rekognition:DetectText
          Resource: '*'

  environment:
    BUCKET_NAME: ${self:custom.s3.bucket}
    USERS_TABLE: ${self:custom.table.users}
    IMAGES_TABLE: ${self:custom.table.images}
    ATTENDANCE_TABLE: ${self:custom.table.attendance}
    USER_ID_HASH_KEY: ${self:custom.hash.userId}
    IMAGE_NAME_HASH_KEY: ${self:custom.hash.imageName}

functions:
  # AUTH FUNCTIONS
  signup:
    handler: handlers/auth/signup.signup
    events:
      - http:
          path: auth/signup
          method: post
          cors: true
  login:
    handler: handlers/auth/login.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  # IMAGE UPLOADER FUNCTIONS
  getSignURL:
    handler: handlers/upload/getSignURL.getSignURL
    events:
      - http:
          path: upload
          method: post
          cors: true

  getListBucket:
    handler: handlers/upload/getListBucket.getListBucket
    events:
      - http:
          path: image
          method: get
          cors: true

  deleteImage:
    handler: handlers/upload/deleteImage.deleteImage
    events:
      - http:
          path: image
          method: delete
          cors: true

  # this function will ONLY be triggered by event trigger when image is uploaded on AWS S3
  writeImageData:
    handler: handlers/upload/writeImageData.writeImageData
    events:
      - s3:
          bucket: ${self:custom.s3.bucket}
          event:
            - s3:ObjectCreated:*
          # rules:
          #   - prefix: /
          #   - suffix: .jpg
          existing: true
  # this function will ONLY be triggered by event streams when image data is written in Images table on DynamoDB
  compareFace:
    handler: handlers/compare/compareFace.compareFace
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt ImagesTable.StreamArn
          # 1 dor 10 l orj irwel event gej vzne.
          batchSize: 10
          startingPosition: LATEST

  # ATTENDANCE FUNCTIONS
  createAttendance:
    handler: handlers/attendance/createAttendance.createAttendance
    events:
      - http:
          path: attendance
          method: post
          cors: true
  # getOwnAttendance:
  #   handler: handlers/getOwnAttendance.getOwnAttendance
  #   events:
  #     - http:
  #         path: attendance/list
  #         method: get
  #         cors: true
  # getSortedAttendance:
  #   handler: handlers/getSortedAttendance.getSortedAttendance
  #   events:
  #     - http:
  #         path: attendance/sort
  #         method: get
  #         cors: true

resources:
  Resources:
    # 1) FOR USER TABLE. When user signs up.
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.table.users}
        # because email is globally UNIQUE...
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          # global sec/index name
          - IndexName: email-index
            KeySchema:
              # Partition key
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    # 2) FOR IMAGES TABLE. When user image is uploaded.
    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: imageName
            AttributeType: S
        KeySchema:
          - AttributeName: imageName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.table.images}
        # MUST Define it. Without it "compareFace" functions "arn: !GetAtt ImagesTable.StreamArn" won't work!!!!!!!
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    # 3) FOR ATTENDANCE TABLE. When user image is compared.
    AttendanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.table.attendance}
    # FOR ATTENDANCE IMAGE BUCKET
    GanzoS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.bucket}
        LifecycleConfiguration:
          Rules:
            - Status: Enabled
              Prefix: original/
            - Status: Enabled
              Prefix: daily/

        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - DELETE
              AllowedOrigins:
                - '*'
    # FOR ATTENDANCE IMAGE BUCKET
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref GanzoS3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::${self:custom.s3.bucket}/*
                # For only list bucket...
                - arn:aws:s3:::${self:custom.s3.bucket}
              Effect: Allow
              Principal: '*'
# Note: Please note that when BillingMode is set to PAY_PER_REQUEST, you can not specify ProvisionedThroughput. Either you provide ProvisionedThroughput RCU, WCU values on the base table and GSI both or make BillingMode on the base table to be PAY_PER_REQUEST and don’t specify ProvisionedThroughput anywhere.

# CorsConfiguration
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors.html#cfn-s3-bucket-cors-corsrule
